/*
 * Rating Service
 * This is the API documentation for the Rating Service, which is part of a microservices-based Rating Application.  This service allows users to add and retrieve ratings for companies, including user-specific and company-specific ratings. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fqts.rating.service.model;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Schema representing the details of a company being rated, including its identity, industry, description, and the average rating score.
 */
@Schema(description = "Schema representing the details of a company being rated, including its identity, industry, description, and the average rating score.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-01T09:34:38.541185546Z[GMT]")

public class CompanyAverageRating {
  @SerializedName("companyId")
  private Integer companyId = null;

  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("industry")
  private String industry = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("averageRating")
  private Float averageRating = null;

  public CompanyAverageRating companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * The unique identifier of the company.
   * @return companyId
  **/
  @Schema(description = "The unique identifier of the company.")
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public CompanyAverageRating companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * The name of the company.
   * @return companyName
  **/
  @Schema(description = "The name of the company.")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public CompanyAverageRating industry(String industry) {
    this.industry = industry;
    return this;
  }

   /**
   * The industry or sector to which the company belongs.
   * @return industry
  **/
  @Schema(description = "The industry or sector to which the company belongs.")
  public String getIndustry() {
    return industry;
  }

  public void setIndustry(String industry) {
    this.industry = industry;
  }

  public CompanyAverageRating description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A brief overview of the company&#x27;s mission, products, services, and core values.
   * @return description
  **/
  @Schema(description = "A brief overview of the company's mission, products, services, and core values.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CompanyAverageRating averageRating(Float averageRating) {
    this.averageRating = averageRating;
    return this;
  }

   /**
   * The average rating score of the company, based on all ratings.
   * @return averageRating
  **/
  @Schema(description = "The average rating score of the company, based on all ratings.")
  public Float getAverageRating() {
    return averageRating;
  }

  public void setAverageRating(Float averageRating) {
    this.averageRating = averageRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyAverageRating companyAverageRating = (CompanyAverageRating) o;
    return Objects.equals(this.companyId, companyAverageRating.companyId) &&
        Objects.equals(this.companyName, companyAverageRating.companyName) &&
        Objects.equals(this.industry, companyAverageRating.industry) &&
        Objects.equals(this.description, companyAverageRating.description) &&
        Objects.equals(this.averageRating, companyAverageRating.averageRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, companyName, industry, description, averageRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyAverageRating {\n");
    
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    averageRating: ").append(toIndentedString(averageRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
