/*
 * Rating Service
 * This is the API documentation for the Rating Service, which is part of a microservices-based Rating Application.  This service allows users to add and retrieve ratings for companies, including user-specific and company-specific ratings. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fqts.rating.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Schema representing the response after successfully adding a rating. It contains the ID of the newly created rating. 
 */
@Schema(description = "Schema representing the response after successfully adding a rating. It contains the ID of the newly created rating. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-01T09:34:38.541185546Z[GMT]")

public class RatingIdResponse {
  @SerializedName("ratingId")
  private Float ratingId = null;

  public RatingIdResponse ratingId(Float ratingId) {
    this.ratingId = ratingId;
    return this;
  }

   /**
   * The unique identifier of the newly added rating.
   * @return ratingId
  **/
  @Schema(description = "The unique identifier of the newly added rating.")
  public Float getRatingId() {
    return ratingId;
  }

  public void setRatingId(Float ratingId) {
    this.ratingId = ratingId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingIdResponse ratingIdResponse = (RatingIdResponse) o;
    return Objects.equals(this.ratingId, ratingIdResponse.ratingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ratingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingIdResponse {\n");
    
    sb.append("    ratingId: ").append(toIndentedString(ratingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
