/*
 * Company Service
 * This is the API documentation for the Company service from the Rating Service project, which is part of a microservice architecture for ratings.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Company;
import io.swagger.client.model.CompanyIdResponse;
import io.swagger.client.model.CompanyList;
import io.swagger.client.model.CompanyUpdateRequest;
import io.swagger.client.model.CreateCompanyRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * Add Company details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addcompanyPostTest() throws Exception {
        CreateCompanyRequest body = null;
        CompanyIdResponse response = api.addcompanyPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get Company detail by Company id
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void companyCompanyIdGetTest() throws Exception {
        Integer companyId = null;
        Company response = api.companyCompanyIdGet(companyId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Delete a Company from the system by companyId
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deletecompanyCompanyIdDeleteTest() throws Exception {
        Integer companyId = null;
        api.deletecompanyCompanyIdDelete(companyId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get all company details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getallcompanyGetTest() throws Exception {
        CompanyList response = api.getallcompanyGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Update Company details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updatecompanyPutTest() throws Exception {
        CompanyUpdateRequest body = null;
        CompanyIdResponse response = api.updatecompanyPut(body);

        // TODO: test validations
    }
}
