#version: '3.8'
services:
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
